version: "3"
volumes:
#    - nextcloud:/data/nextcloud
#    - mysql:/data/mysql
#    - php:/data/php
#    - nginx-conf:/data/nginx/nginx.conf
#    - nginx-logs:/data/nginx/logs
  nextcloud:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /data/nextcloud
  mysql:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/mysql
  php:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/php
  php-log:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/php/logs
  nginx-logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/nginx/logs
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx-logs:/var/log/nginx/log
      - nextcloud:/var/www/nextcloud
  php:
    image: devilbox/php-fpm:5.4-work-0.128
    volumes:
      - php:/var/www/html
      - nextcloud:/var/www/nextcloud
      - php-log:/var/log/php-fpm
      - /data/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
  mysql:
    image: mysql:5.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_PASSWORD=123456
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - mysql
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mysql
