version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - /root/html:/usr/share/nginx/html
      - /root/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/logs:/var/log/nginx/log
  php:
    image: devilbox/php-fpm:5.4-work-0.128
    volumes:
      - /root/html:/var/www/html
  mysql: 
    image: mysql:5.6
    environment:
    - MYSQL_ROOT_PASSWORD=123456    
